<section class="section section-md">
	<div class="container top-carga">
		<div class="row">
			<div class="col-3">
			</div>
			<div class="col">				
				<div class="row">
					<div class="col-12 titulo-formulario tituloo  font-weight-bold wow-outer linea">
							Publicar
					</div>
					<div class="col-12 furmulario">
						<div class="form-group row">
						  <label for="example-text-input" class="col-2 col-form-label">Text</label>
						  <div class="col-10">
						    <input class="form-control" type="text" value="Artisanal kale" id="example-text-input">
						  </div>
							</div>
							<div class="form-group row">
							  <label for="example-search-input" class="col-2 col-form-label">Search</label>
							  <div class="col-10">
							    <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
							  </div>
							</div>
							<div class="form-group row">
							  <label for="example-email-input" class="col-2 col-form-label">Email</label>
							  <div class="col-10">
							    <input class="form-control" type="email" value="bootstrap@example.com" id="example-email-input">
							  </div>
							</div>
							<div class="form-group row">
							  <label for="example-url-input" class="col-2 col-form-label">URL</label>
							  <div class="col-10">
							    <input class="form-control" type="url" value="https://getbootstrap.com" id="example-url-input">
							  </div>
							</div>
							<div class="form-group row">
							  <label for="example-tel-input" class="col-2 col-form-label">Telephone</label>
							  <div class="col-10">
							    <input class="form-control" type="tel" value="1-(555)-555-5555" id="example-tel-input">
							  </div>
							</div>
							<div>
								<div id='carga-img' class="dropzone"></div>	  
							</div>
							<div class="col-12 wow-outer">
          					 <center> <a class="button button-primary button-winona button-md" href="#" id="btn_enviar">
          					    <div class="content-original">
          					      Enviar Mensaje
          					    </div>
          					    <div class="content-dubbed">
          					      Enviar Mensaje
          					    </div>
          					  </a></center>
          					</div>
						</div>
					</div>
			</div>
			<div class="col-3">
				
					

			</div>
								
		</div>
	</div>
</section>
