<section class="section novi-background section-sm">
  <div class="container">
    <div class="row margin-top">
      <div class="col-lg-10 col-xl-8 div-galeria-principal">
        <h6 class="linea font-weight-bold"><?php echo $retVal = ($this->bn==1) ? $this->datos['titulo'] : '' ; ?></h6>
        	<div class="col-md-12">
          	<ul id="lightSlider">                                  
              <?php for ($i=0; $i < count($this->fotos) ; $i++):?>                      
                <li data-thumb="<?php echo BASE_URL.$this->fotos[$i]['grande'] ?>">
                  <img src="<?php echo BASE_URL.$this->fotos[$i]['grande'] ?>"/>
                </li>
              <?php endfor; ?>
            </ul>
          </div>
      </div>
      <div class="col-lg-2 col-xl-4">
        <h6 class="linea">Contacto</h6>
        <div class="col-md-12 formulario_contacto">
          <form>
            <div class="form-group">
              <label for="exampleFormControlInput1">Nombre</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="nombre">
            </div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Telefono</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="telefono">
            </div>

            <div class="form-group">
              <label for="exampleFormControlInput1">Email</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
            </div>           
          
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Mensaje</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="col-12 wow-outer">
             <center> <a class="button button-primary button-winona button-md" href="#">
                <div class="content-original">
                  Enviar Mensaje
                </div>
                <div class="content-dubbed">
                  Enviar Mensaje
                </div>
              </a></center>
            </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section novi-background section-md section-last bg-gray-100">
	<div class="container">
    	<div class="col-lg-10 col-xl-8 wow-outer">
    		<h4 class="linea">Detalles de la Propiedad</h4>
    		<div class="row row-30">
        		<div class="col-md-12 wow-outer">
        	 		<div class="wow fadeSlideInUp">
        	 			<ul>
        	 				<li><?php echo $retVal = ($this->bn==1) ? $this->datos['direccion'] : '' ; ?></li>
        	 				<li><?php echo $retVal = ($this->bn==1) ? $this->datos['referencia'] : '' ; ?></li>
        	 				<li><?php echo $retVal = ($this->bn==1) ? $this->datos['Precio'] : '' ; ?></li>
        	 				<li><?php echo $retVal = ($this->bn==1) ? $this->datos['contrato'] : '' ; ?></li>
        	 				<li><?php echo $retVal = ($this->bn==1) ? $this->datos['espacio'] : '' ; ?></li>
        	 				<li><?php echo $retVal = ($this->bn==1) ? $this->datos['cantp'] : '' ; ?></li>
        	 				<li><?php echo $retVal = ($this->bn==1) ? $this->datos['cantb'] : '' ; ?></li>
                  <li><?php echo $retVal = ($this->bn==1) ? $this->datos['Canta'] : '' ; ?></li>
        	 			</ul>
        	 		</div>
        	 	</div>
        	</div>
        	<div class="row row-30">
        	 	<div class="col-md-12 wow-outer">
        	 	  <div class="wow fadeSlideInUp">
        	 	    <label class="">Descripcion</label><br>
                  <?php echo $retVal = ($this->bn==1) ? $this->datos['descrip'] : '' ; ?>
        	 	  </div>
        	 	</div>
    		</div>
    	</div>
	</div>
</section>