<section class="section novi-background section-sm">
  <div class="container">
    <div class="row margin-top">
      <div class="col-lg-10 col-xl-8 div-galeria-principal">
        <h6 class=" font-weight-bold">Nombre propiedad cargado dinamicamente</h6>      
        	<div class="col-md-12">
          		<ul id="lightSlider">
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg"/>
   				    	<h3>First Slide</h3>
   				    	<p>Lorem ipsum Cupidatat quis pariatur anim.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>Second Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>3 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>4 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>5 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>6 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>7 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   				</ul>
            </div>
      </div>
      <div class="col-lg-2 col-xl-4">
        	<h6 class="linea">Contacto</h6>
        <div class="col-md-12 formulario_contacto">
          <form>
            <div class="form-group">
              <label for="exampleFormControlInput1">Nombre</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="nombre">
            </div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Telefono</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="telefono">
            </div>

            <div class="form-group">
              <label for="exampleFormControlInput1">Email</label>
              <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
            </div>           
          
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Mensaje</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>
            <div class="col-12 wow-outer">
             <center> <a class="button button-primary button-winona button-md" href="#">
                <div class="content-original">
                  Enviar Mensaje
                </div>
                <div class="content-dubbed">
                  Enviar Mensaje
                </div>
              </a></center>
            </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section novi-background section-md section-last bg-gray-100">
	<div class="container">
    	<div class="col-lg-10 col-xl-8 wow-outer">
    		<h4 class="linea">Detalles de la Propiedad</h4>
    		<div class="row row-30">
        		<div class="col-md-12 wow-outer">
        	 		<div class="wow fadeSlideInUp">
        	 			<ul>
        	 				<li>Precio (arriendo/costo)</li>
        	 				<li>Tipo de inmueble</li>
        	 				<li>Direccion</li>
        	 				<li>Region</li>
        	 				<li>Ciudad</li>
        	 				<li>Comuna</li>
        	 				<li>Superficie total</li>
        	 				<li>Superficie Construida</li>
        	 				<li>Año de construccion</li>
        	 				<li>Dormitorios</li>
        	 				<li>Baños</li>
        	 				<li>Estacionamiento</li>
        	 			</ul>
        	 		</div>
        	 	</div>
        	</div>
        	<div class="row row-30">
        	 	<div class="col-md-12 wow-outer">
        	 	  <div class="wow fadeSlideInUp">
        	 	    <label class="">Descripcion</label>
        	 	  </div>
        	 	</div>
    		</div>
    	</div>
	</div>
</section>