<section class="section novi-background section-sm">
  <div class="container">
    <div class="row">
      <div class="col-lg-10 col-xl-8 div-galeria-principal">
        <h6>Nombre propiedad cargado dinamicamente</h6>      
        	<div class="col-md-12">
          		<ul id="lightSlider">
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg"/>
   				    	<h3>First Slide</h3>
   				    	<p>Lorem ipsum Cupidatat quis pariatur anim.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>Second Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>3 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>4 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>5 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>6 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   					<li data-thumb="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg">
   						<img src="<?php echo BASE_URL ?>public/img/grid-blog-1-571x353.jpg" />
   				    	<h3>7 Slide</h3>
   				    	<p>Lorem ipsum Excepteur amet adipisicing fugiat velit nisi.</p>
   					</li>
   				</ul>
            </div>
      </div>
      <div class="col-lg-2 col-xl-4">
        	<h6>Contacto</h6>
        <div class="col-md-12">
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section novi-background section-md section-last bg-gray-100">
	<div class="container">
    	<div class="col-lg-10 col-xl-8 wow-outer">
    		<h4>Detalles de la Propiedad</h4>
    		<div class="row row-30">
        		<div class="col-md-12 wow-outer">
        	 		<div class="wow fadeSlideInUp">
        	 			<ul>
        	 				<li>Precio (arriendo/costo)</li>
        	 				<li>Tipo de inmueble</li>
        	 				<li>Direccion</li>
        	 				<li>Region</li>
        	 				<li>Ciudad</li>
        	 				<li>Comuna</li>
        	 				<li>Superficie total</li>
        	 				<li>Superficie Construida</li>
        	 				<li>Año de construccion</li>
        	 				<li>Dormitorios</li>
        	 				<li>Baños</li>
        	 				<li>Estacionamiento</li>
        	 			</ul>
        	 		</div>
        	 	</div>
        	</div>
        	<div class="row row-30">
        	 	<div class="col-md-12 wow-outer">
        	 	  <div class="wow fadeSlideInUp">
        	 	    <label class="">Descripcion</label>
        	 	  </div>
        	 	</div>
    		</div>
    	</div>
	</div>
</section>