<!-- <div class="container">
	  		<div id="map">div map</div>
	  </div> -->
	 <div class="row justify-content-center">
     <div class="col-sm-3">
  <img class="img-logo" width="100%" src="<?php echo BASE_URL ?>public/img/logos/logo.png">

</div>
 


   </div>


<div class="row justify-content-center">
     <div class="col-sm-2">
  <img class="img-logo" width="100%" src="<?php echo BASE_URL ?>public/img/logos/imgg.gif">

</div>
 


   </div>