	  <section class="section section-md">
	  	<div class="container">
	  		<div id="map">div map</div>
	  	</div>
	  </section>
      <section class="section novi-background section-md text-center">
        <div class="container">
          <h3 class="text-uppercase font-weight-bold wow-outer tituloo"><span class="wow slideInDown">Popular properties</span></h3>

          <div class="row row-lg-50 row-35 offset-top-2">
            
            <?php for($i=0; $i < count($this->propiedades) ; $i++):?>
            <div class="col-xl-3 col-gl-4 col-md-6 col-sm-12 col-12 wow-outer">
              <!-- Post Modern-->
              <article class="post-modern wow slideInLeft">
                <?php if($i==0): ?>
                  <a class="post-modern-media propiedad articulo" href="#" data-id="<?php print_r($this->propiedades[$i]['id_propiedad']); ?>" data-posicion='ultimo'>
                <?php elseif($i==(count($this->propiedades)-1)): ?>
                  <a class="post-modern-media propiedad articulo" href="#" data-id="<?php print_r($this->propiedades[$i]['id_propiedad']); ?>" data-posicion='primero'>
                <?php else: ?>
                  <a class="post-modern-media propiedad articulo" href="#" data-id="<?php print_r($this->propiedades[$i]['id_propiedad']); ?>" data-posicion='intermedio'>
                <?php endif;?>
                <?php if(isset($this->propiedades[$i]['fotos'][0]['grande'])): ?>
                  <img src="<?php echo BASE_URL.$this->propiedades[$i]['fotos'][0]['grande'];?>" alt="" width="571" height="353">
                <?php else: ?>
                  <img src="<?php echo BASE_URL ?>public/img/casa_out.png" alt="" width="571" height="353">
                <?php endif;?>
              </a>
                <h4 class="post-modern-title">
                <?php if($i==0): ?>
                  <a class="post-modern-title propiedad" href="#" data-id="<?php print_r($this->propiedades[$i]['id_propiedad']); ?>" data-posicion='ultimo'>                  
                <?php elseif($i==(count($this->propiedades)-1)): ?>
                  <a class="post-modern-title propiedad" href="#" data-id="<?php print_r($this->propiedades[$i]['id_propiedad']); ?>" data-posicion='primero'>                  
                <?php else: ?>
                  <a class="post-modern-title propiedad" href="#" data-id="<?php print_r($this->propiedades[$i]['id_propiedad']); ?>" data-posicion='intermedio'>                  
                <?php endif;?>
                  <?php print_r($this->propiedades[$i]['titulo']); ?>
                </a></h4>
                <div class=" row descrip">
          		<div class="col-3 desc"><i class="fa fa-car" aria-hidden="false"></i><?php print_r($this->propiedades[$i]['cantp']); ?></div>
          		<div class="col-3 desc"><i class="fa fa-bath" aria-hidden="true"></i><?php print_r($this->propiedades[$i]['cantb']); ?></div>
          		<div class="col-3 desc"><i class="fa fa-bed" aria-hidden="true"></i><?php print_r($this->propiedades[$i]['Canta']); ?></div>
          		<div class="col-3 desc"><i class="fa fa-building" aria-hidden="true"></i><?php print_r($this->propiedades[$i]['Canta']); ?></div>
                  	</div>
                <ul class="post-modern-meta">                  
                  <li><?php print_r($this->propiedades[$i]['espacio']); ?></li>
                  <li><?php print_r($this->propiedades[$i]['contrato']); ?></li>
                </ul>
                
              </article>
            </div>
          <?php endfor;?>
                       
            <div class="col-12 wow-outer"><a class="button button-primary button-winona button-md" href="#"><div class="content-original">Ver mas Propiedades</div><div class="content-dubbed">Ver mas Propiedades</div></a></div>
          </div>



        </div>
      </section>


    <section class="section novi-background section-lg bg-gray-100">
        <div class="container">
          <div class="row row-30">
            <div class="col-sm-6 col-lg-4 wow-outer">
             
              <article class="box-minimal">
                <div class="wow fadeIn"></div>
                <div class="box-minimal-main wow-outer">
                  <h4 class="box-minimal-title wow slideInDown"><i class="fa fa-car" aria-hidden="false"></i> Qualified Employees</h4>
                  <p class="wow fadeInUpSmall">Our team consists of more than 20 qualified and experienced real estate brokers and property managers ready to help you.</p>
                </div>
              </article>
            </div>
            <div class="col-sm-6 col-lg-4 wow-outer">
              
              <article class="box-minimal">
                <div class="wow fadeIn" data-wow-delay=".1s"></div>
                <div class="box-minimal-main wow-outer">
                  <h4 class="box-minimal-title wow slideInDown" data-wow-delay=".1s"><i class="fa fa-bath" aria-hidden="true"></i> Free Consultations</h4>
                  <p class="wow fadeInUpSmall" data-wow-delay=".1s">Our acquaintance with a client always begins with a free consultation to find out what kind of property they are looking for.</p>
                </div>
              </article>
            </div>
            <div class="col-sm-6 col-lg-4 wow-outer">
             
              <article class="box-minimal">
                <div class="wow fadeIn" data-wow-delay=".2s"></div>
                <div class="box-minimal-main wow-outer">
                  <h4 class="box-minimal-title wow slideInDown" data-wow-delay=".2s"><i class="fa fa-bath" aria-hidden="true"></i> 100% Guaranteed</h4>
                  <p class="wow fadeInUpSmall" data-wow-delay=".2s">All the results that you get from our realtors are 100% guaranteed to offer you the best choice of properties throughout the USA.</p>
                </div>
              </article>
            </div>
          </div>
        </div>
      </section> 


      <!-- Services-->
      <section class="section novi-background section-lg text-center">
        <div class="container">
          <h3 class="text-uppercase">Residential property categories</h3>
          <p><span class="text-width-1">At our agency, we work with various types of residential real estate property. You can find out more about our properties by browsing our website.</span></p>
          <div class="row row-35 row-xxl-70 offset-top-2">
            <div class="col-sm-6 col-lg-3">
              <!-- Thumbnail Light-->
              <article class="thumbnail-light"><a class="thumbnail-light-media" href="#"><img class="thumbnail-light-image" src="<?php echo BASE_URL ?>public/img/service-thumbnail-1-270x300.jpg" alt="" width="270" height="300"/></a>
                <h4 class="thumbnail-light-title"><a href="#">Single-Family Homes</a></h4>
              </article>
            </div>
            <div class="col-sm-6 col-lg-3">
              <!-- Thumbnail Light-->
              <article class="thumbnail-light"><a class="thumbnail-light-media" href="#"><img class="thumbnail-light-image" src="<?php echo BASE_URL ?>public/img/service-thumbnail-2-270x300.jpg" alt="" width="270" height="300"/></a>
                <h4 class="thumbnail-light-title"><a href="#">Townhouses</a></h4>
              </article>
            </div>
            <div class="col-sm-6 col-lg-3">
              <!-- Thumbnail Light-->
              <article class="thumbnail-light"><a class="thumbnail-light-media" href="#"><img class="thumbnail-light-image" src="<?php echo BASE_URL ?>public/img/service-thumbnail-3-270x300.jpg" alt="" width="270" height="300"/></a>
                <h4 class="thumbnail-light-title"><a href="#">Multi-Family Homes</a></h4>
              </article>
            </div>
            <div class="col-sm-6 col-lg-3">
              <!-- Thumbnail Light-->
              <article class="thumbnail-light"><a class="thumbnail-light-media" href="#"><img class="thumbnail-light-image" src="<?php echo BASE_URL ?>public/img/service-thumbnail-4-270x300.jpg" alt="" width="270" height="300"/></a>
                <h4 class="thumbnail-light-title"><a href="#">Condominiums</a></h4>
              </article>
            </div>
            <div class="col-md-12 wow-outer"><a class="button button-primary button-winona button-md" href="#">view all properties</a></div>
          </div>
        </div>
      </section>
      <!-- Best offer-->
      <section class="section novi-background section-1 bg-primary-darker text-center" style="background-image: url(<?php echo BASE_URL ?>public/img/bg-1-1920-455.jpg);">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-sm-10 col-lg-7 col-xl-6">
              <h3 class="wow-outer"><span class="wow slideInDown text-uppercase">Best offers</span></h3>
              <p class="heading-subtitle">of September</p>
              <p class="wow-outer offset-top-4"><span class="wow slideInDown" data-wow-delay=".05s">With a variety of accountants available at our company, you can always choose one that fits your corporate requirements.</span></p>
              <div class="wow-outer button-outer"><a class="button button-primary-white button-winona wow slideInDown" href="#" data-wow-delay=".1s">Read more</a></div>
            </div>
          </div>
        </div>
      </section>

